cryspen/libcrux

src/kem/kyber768.rs
src/kem/kyber768/compress.rs
src/kem/kyber768/field_element.rs
src/kem/kyber768/ntt.rs
src/kem/kyber768/parameters.rs
src/kem/kyber768/sampling.rs
src/kem/kyber768/serialize.rs
src/kem/kyber768/utils/field.rs

I added some code for barrett reduction, and tried to remove spurious modulo operations whereever I could.

Reworking field operations.

---

Cargo.toml
src/jasmin/sha3.rs
sys/libjade/Cargo.toml
sys/libjade/build.rs
sys/platform/Cargo.toml
sys/platform/src/lib.rs
sys/platform/src/linux_arm.rs
sys/platform/src/macos_arm.rs
sys/platform/src/test.rs
sys/platform/src/x86.rs

The patch uses `cc` library to compile libjade instead of clang commands and create `libcrux_platform` package to detect cpu features.

Import sys/libjade/build.rs from franziskus/hacl-sys branch

---

build.rs

Some functions in `aead.rs` don't support `aarch64` yet, this patch only enables `aes-ni` configuration on `x86_64/x86` architectures.

Only Enable aes-ni configuration on x86_64/x86

---

src/kem/kyber768.rs
src/kem/kyber768/arithmetic.rs
src/kem/kyber768/compress.rs
src/kem/kyber768/constant_time_ops.rs
src/kem/kyber768/conversions.rs
src/kem/kyber768/ind_cpa.rs
src/kem/kyber768/ntt.rs
src/kem/kyber768/parameters.rs
src/kem/kyber768/sampling.rs
src/kem/kyber768/serialize.rs

- Where possible, after matrix/vector multiplication, leave the result in montgomery form and convert it back to normal form after the inverse NTT
- Use i32s instead of i16s for field elements
- Applied some changes suggested by `cargo clippy`

Yet more kyber optimizations

---

sys/hacl/build.rs
sys/hacl/c/config/vale-aes.h
sys/hacl/c/vale/include/Vale.h
sys/hacl/c/vale/src/aesgcm-x86_64-darwin.S
sys/hacl/c/vale/src/aesgcm-x86_64-linux.S
sys/hacl/c/vale/src/aesgcm-x86_64-mingw.S
sys/hacl/c/vale/src/aesgcm-x86_64-msvc.asm

This patch imports Vale assembly files of AES-GCM mode and supports building these files in Hacl.

Compile Vale AESGCM in hacl

---

proofs/fstar/extraction/Libcrux.Kem.Kyber768.Arithmetic.fst
proofs/fstar/extraction/Libcrux.Kem.Kyber768.Compress.fst
proofs/fstar/extraction/Libcrux.Kem.Kyber768.Constant_time_ops.fst
proofs/fstar/extraction/Libcrux.Kem.Kyber768.Conversions.fst
proofs/fstar/extraction/Libcrux.Kem.Kyber768.Ind_cpa.fst
proofs/fstar/extraction/Libcrux.Kem.Kyber768.Ntt.Kyber_polynomial_ring_element_mod.fst
proofs/fstar/extraction/Libcrux.Kem.Kyber768.Ntt.fst
proofs/fstar/extraction/Libcrux.Kem.Kyber768.Parameters.Hash_functions.fst
proofs/fstar/extraction/Libcrux.Kem.Kyber768.Parameters.fst
proofs/fstar/extraction/Libcrux.Kem.Kyber768.Sampling.fst
proofs/fstar/extraction/Libcrux.Kem.Kyber768.Serialize.fst
proofs/fstar/extraction/Libcrux.Kem.Kyber768.fst
proofs/fstar/extraction/Libcrux.Kem.fst
src/ecdh.rs
src/kem/kyber768.rs
src/kem/kyber768/arithmetic.rs
src/kem/kyber768/conversions.rs
src/kem/kyber768/ind_cpa.rs
src/kem/kyber768/ntt.rs

Some small changes to make kyber extract to F*.
The F* extraction is in the proofs directory.
This needs https://github.com/hacspec/hacspec-v2/pull/246 to be merged for extraction.
Then the extraction can be done with `cargo hax into -i '-** +kem::kyber768::** -kem::kyber768::arithmetic::mutable_operations::**' fstar`.

kyber extraction

---

proofs/fstar/extraction/Libcrux.Kem.Kyber768.Compress.fst
proofs/fstar/extraction/Libcrux.Kem.Kyber768.Conversions.fst
proofs/fstar/extraction/Libcrux.Kem.Kyber768.Serialize.fst
src/kem/kyber768/compress.rs
src/kem/kyber768/conversions.rs
src/kem/kyber768/serialize.rs

Make `compress::compress_q` in the reference code look more like `compress::compress_d` in the specification.

Refactoring Kyber ref for F-star proofs

---

src/kem/kyber/hash_functions.rs
src/kem/kyber/ind_cpa.rs

This isn't taking it all the way. But is probably the best we can do generically.
The `XOFx4` function needs to be replaced with the real deal once that exists.

4 x keccak

---

.github/workflows/hax.yml
.gitignore
hax-driver.py
proofs/fstar/extraction/Makefile

This Makefile lists files that should be fully typechecked, and those that should be typechecked while admitting SMT queries. Over time, we expect more modules to be promoted to VERIFIED.

Makefile for verification

---

hax-driver.py
proofs/fstar/extraction/Libcrux.Kem.Kyber.Arithmetic.fst
proofs/fstar/extraction/Libcrux.Kem.Kyber.Arithmetic.fsti
proofs/fstar/extraction/Libcrux.Kem.Kyber.Compress.fst
proofs/fstar/extraction/Libcrux.Kem.Kyber.Compress.fsti
proofs/fstar/extraction/Libcrux.Kem.Kyber.Constant_time_ops.fst
proofs/fstar/extraction/Libcrux.Kem.Kyber.Constant_time_ops.fsti
proofs/fstar/extraction/Libcrux.Kem.Kyber.Constants.fsti
proofs/fstar/extraction/Libcrux.Kem.Kyber.Conversions.fst
proofs/fstar/extraction/Libcrux.Kem.Kyber.Hash_functions.fst
proofs/fstar/extraction/Libcrux.Kem.Kyber.Hash_functions.fsti
proofs/fstar/extraction/Libcrux.Kem.Kyber.Ind_cpa.fst
proofs/fstar/extraction/Libcrux.Kem.Kyber.Ind_cpa.fsti
proofs/fstar/extraction/Libcrux.Kem.Kyber.Kyber1024.fst
proofs/fstar/extraction/Libcrux.Kem.Kyber.Kyber1024.fsti
proofs/fstar/extraction/Libcrux.Kem.Kyber.Kyber512.fst
proofs/fstar/extraction/Libcrux.Kem.Kyber.Kyber512.fsti
proofs/fstar/extraction/Libcrux.Kem.Kyber.Kyber768.fst
proofs/fstar/extraction/Libcrux.Kem.Kyber.Kyber768.fsti
proofs/fstar/extraction/Libcrux.Kem.Kyber.Matrix.fst
proofs/fstar/extraction/Libcrux.Kem.Kyber.Matrix.fsti
proofs/fstar/extraction/Libcrux.Kem.Kyber.Ntt.fst
proofs/fstar/extraction/Libcrux.Kem.Kyber.Ntt.fsti
proofs/fstar/extraction/Libcrux.Kem.Kyber.Sampling.fst
proofs/fstar/extraction/Libcrux.Kem.Kyber.Sampling.fsti
proofs/fstar/extraction/Libcrux.Kem.Kyber.Serialize.fst
proofs/fstar/extraction/Libcrux.Kem.Kyber.Serialize.fsti
proofs/fstar/extraction/Libcrux.Kem.Kyber.fst
proofs/fstar/extraction/Libcrux.Kem.Kyber.fsti

This PR enables the `--interfaces` option to `cargo hax` and refreshes the extraction of Kyber

Kyber: F*: enable the `--interfaces` option for most modules

---

hax-driver.py
proofs/fstar/extraction/Libcrux.Digest.fsti
proofs/fstar/extraction/Libcrux.Kem.Kyber.Hash_functions.fst

The CI of libcrux was broken by hax' PR https://github.com/hacspec/hax/pull/475
This PR makes hax ignores a few modules containg unsafe code (under `libcrux_platform`)

Kyber: hax: fix extraction 

---

.github/workflows/hax.yml
hax-driver.py
proofs/fstar/extraction-edited.patch
proofs/fstar/extraction-secret-independent.patch
proofs/fstar/extraction/Libcrux.Digest.fst
proofs/fstar/extraction/Libcrux.Digest.fsti
proofs/fstar/extraction/Libcrux.Kem.Kyber.Hash_functions.fst
proofs/fstar/extraction/Makefile
proofs/fstar/extraction/clean.sh
src/kem/kyber/hash_functions.rs
sys/platform/proofs/fstar/extraction/Libcrux_platform.Platform.fsti
sys/platform/proofs/fstar/extraction/Libcrux_platform.fsti
sys/platform/src/lib.rs

This PR:
- update F*;
- makes F* extraction stable across hardware (well, I hope, I cannot try);
- fixes the Makefiles in `proofs/extraction/fstar` so that they use the correct folder for Libcrux_platform;
- makes CI check snapshots are up to date;
- cut CI time for the `hax` job in two by installing Hax from Nix (going from ~12 minutes to ~1 minute)

Fix hax cfg issues

---

src/hacl/drbg.rs

This is needed for achieving `Sync` using a Mutex. Since there is no uncoordinated shared state with other threads, it is safe to impl `Send`.

impl Send for Drbg

---

libcrux-ml-kem/Cargo.toml
libcrux-sha3/src/x4/internal.rs

Only use the `simd256` feature, not the config.

Drop simd256 cfg from SHA3 crate

---

.gitignore
libcrux-ml-kem/.gitignore
libcrux-ml-kem/c.sh
libcrux-ml-kem/src/sampling.rs
libcrux-ml-kem/src/simd/portable.rs

This makes it such that Charon can extract the portable code. Eurydice still fails.
This works towards #236 and #200.

Workarounds for Charon issues in portable ml-kem

---

build.rs

When setting LIBCRUX_DISABLE_SIMD128 (SIMD256), the corresponding simd config will not be enabled even when available.

allow disabling simd in libcrux

---

benchmarks/benches/kyber768.rs
kyber-c.yaml
proofs/fstar/extraction-edited.patch
proofs/fstar/extraction-secret-independent.patch
proofs/fstar/extraction/Libcrux.Kem.Kyber.Ind_cpa.fst
proofs/fstar/extraction/Libcrux.Kem.Kyber.Ind_cpa.fsti
proofs/fstar/extraction/Libcrux.Kem.Kyber.Kyber1024.fst
proofs/fstar/extraction/Libcrux.Kem.Kyber.Kyber1024.fsti
proofs/fstar/extraction/Libcrux.Kem.Kyber.Kyber512.fst
proofs/fstar/extraction/Libcrux.Kem.Kyber.Kyber512.fsti
proofs/fstar/extraction/Libcrux.Kem.Kyber.Kyber768.fst
proofs/fstar/extraction/Libcrux.Kem.Kyber.Kyber768.fsti
proofs/fstar/extraction/Libcrux.Kem.Kyber.fst
proofs/fstar/extraction/Libcrux.Kem.Kyber.fsti
src/kem.rs
src/kem/kyber.rs
src/kem/kyber/ind_cpa.rs
src/kem/kyber/kyber1024.rs
src/kem/kyber/kyber512.rs
src/kem/kyber/kyber768.rs
tests/kyber.rs

In addition to Karthik's API improvements, this PR contains a few more goodies on top, notably:
- generating code for all three variants of kyber, but in separate files
- putting all of the shared code in a header where everything is marked as static inline
- updated config.yaml for all of the above
- addition of a few well-chosen type declarations to generate prettier C code
I think this would be worth merging now.
PR on the hacl-packages side forthcoming

Libcrux optimize decap

---

proofs/fstar/extraction-edited.patch
proofs/fstar/extraction-secret-independent.patch
proofs/fstar/extraction/Libcrux.Kem.Kyber.fst
proofs/fstar/extraction/Libcrux.Kem.Kyber.fsti
proofs/fstar/patches.sh

This PR regenerates patches following hacspec/hax#676.
Once again, either this CI or Hax' CI should be bypassed.

Refresh patches, followup for hax PR hacspec/hax#676

---

libcrux-ml-kem/hax.py

The hax.py merged in PR #308 was only generating .fsti files for libcrux-ml-kem.
This PR fixes that bug.

Fixing hax.py to generate .fst files

---

Cargo.lock
libcrux-ecdh/Cargo.toml
libcrux-ecdh/tests/p256.rs
libcrux-ecdh/tests/x25519.rs

This PR gets rid of the `libcrux` dependency for testing in `libcrux-ecdh`. To do this, I've replaced the `libcrux` Drbg with `OsRng`, that was previously only used for the `wasm32` target.

Drop `libcrux` dependency in `libcrux-ecdh`

---

Cargo.lock
libcrux-kem/Cargo.toml
libcrux-kem/README.md
libcrux-kem/src/kem.rs

Same procedure as #347, replacing `libcrux` `Drbg` with `OsRng`.

Remove `libcrux` dependency in `libcrux-kem`

---

.github/workflows/c.yml
.github/workflows/checks.yml
.github/workflows/hax.yml
.github/workflows/mlkem.yml
.github/workflows/nix.yml
.github/workflows/rust.yml

This PR introduces `merge_queue` triggers for all jobs that are run on PRs and makes it so that benchmarks are only run on the `merge_queue` event, or when manually triggered.

Run benchmarks on merge queue, or manually

---

libcrux-ml-dsa/src/arithmetic.rs
libcrux-ml-dsa/src/encoding/commitment.rs
libcrux-ml-dsa/src/encoding/error.rs
libcrux-ml-dsa/src/encoding/gamma1.rs
libcrux-ml-dsa/src/encoding/t0.rs
libcrux-ml-dsa/src/encoding/t1.rs
libcrux-ml-dsa/src/matrix.rs
libcrux-ml-dsa/src/ml_dsa_generic.rs
libcrux-ml-dsa/src/sample.rs
libcrux-ml-dsa/src/simd/portable.rs
libcrux-ml-dsa/src/simd/portable/arithmetic.rs
libcrux-ml-dsa/src/simd/portable/encoding.rs
libcrux-ml-dsa/src/simd/portable/encoding/commitment.rs
libcrux-ml-dsa/src/simd/portable/encoding/error.rs
libcrux-ml-dsa/src/simd/portable/encoding/gamma1.rs
libcrux-ml-dsa/src/simd/portable/encoding/t0.rs
libcrux-ml-dsa/src/simd/portable/encoding/t1.rs
libcrux-ml-dsa/src/simd/traits.rs

- hints are now represented using `i32`s instead of `bool`s.

ML-DSA: Moved all the encoding code and more of the arithmetic code to a vectorized structure.

---

.docker/c/Dockerfile
.docker/c/install.sh
.docker/c/setup.sh

This PR is a first step towards getting C extraction on CI:
- Update the revisions of HACL*, Charon, Karamel and Eurydice to their current latest main branch state.
- Fix depencencies for these tools in the Docker image.
With this, the image could be published I think.

Update C extraction Docker file

---

specs/kyber/Cargo.toml

Updates Kyber spec dependency on `libcrux`/`libcrux-ml-kem`.

Fix specs CI

---

.github/workflows/mlkem.yml
libcrux-ml-kem/.cargo/config.toml

We don't need to test the old version, let's use the pre-verification version that we actually use and work on.

use pre-verification feature for ml-kem on CI runs

---

src/digest.rs
src/hacl/sha2.rs
tests/sha2.rs

We need these implementations for implementing a provider that requires these features.
`Send` should be safe, since there is no other thread in C-land that operates on the data in the hash state. We already did the same for Drbg: #205

Implement `Clone` and `Send` for SHA2 state and hasher types

---

libcrux-ml-kem/src/mlkem1024.rs
libcrux-ml-kem/src/mlkem512.rs
libcrux-ml-kem/src/mlkem768.rs

https://github.com/hacspec/hax/pull/846 makes `fstar::before` and `fstar::after` chunks of code default to implementation files (fst).
This commit backports that change and makes some code go explicitly to interfaces.

fix(mlkem/fstar): fix regression introduced by hacspec/hax#864

---

libcrux-ml-kem/proofs/fstar/extraction/Libcrux_ml_kem.Vector.Portable.Serialize.fst
libcrux-ml-kem/proofs/fstar/extraction/Libcrux_ml_kem.Vector.Portable.Serialize.fsti
libcrux-ml-kem/src/vector/portable/serialize.rs

This PR adds lemmas for portable serialize/deserialize functions. The proofs for lemmas are based on the tactic of the following PR https://github.com/cryspen/libcrux/pull/549 and it takes long to verify (specifically for those lemmas with big ranges). It comments out the lemmas for serialize_5/deserialize_5 and serialize_11/deserialize_11 get rid of workloads of lower priority.
For now, the lemmas serialize_1/deserialize_1 and serialize_4/deserialize_4 are tested. Currently, I am verifying the lemmas all together in a one run..

Add lemmas for Portable serialize/deserialize functions

---

libcrux-ml-kem/hax.py

Fixes build failure that happened here: https://github.com/cryspen/libcrux/actions/runs/10677857822/job/29593758713?pr=555
This comes after merging https://github.com/hacspec/hax/pull/867 that rejects any AST containing unsafe blocks.
We still extract the interfaces for these functions.

Remove unsafe code from include to avoid being rejected by hax.

---

.github/workflows/mldsa.yml
libcrux-ml-dsa/benches/bench_utils.rs
libcrux-ml-dsa/benches/ml-dsa.rs

As a first step in addressing #571, it would be nice to be able to run some benchmarks. Unfortunately, with #558, I broke benchmarks on `main` and didn't notice. This fixes the benchmarks and includes a `--no-run` build of the benchmarks on CI for the future.

Fix ML-DSA benchmarks

---

Cargo.lock
Cargo.toml
fstar-helpers/fstar-bitvec/Tactics.GetBit.fst
fstar-helpers/fstar-bitvec/Tactics.Seq.fst
libcrux-ml-kem/proofs/fstar/extraction/Libcrux_ml_kem.Polynomial.fst
libcrux-ml-kem/proofs/fstar/extraction/Libcrux_ml_kem.Polynomial.fsti
libcrux-ml-kem/proofs/fstar/extraction/Libcrux_ml_kem.Sampling.fst
libcrux-ml-kem/proofs/fstar/extraction/Libcrux_ml_kem.Sampling.fsti
libcrux-ml-kem/proofs/fstar/extraction/Libcrux_ml_kem.Serialize.fst
libcrux-ml-kem/proofs/fstar/extraction/Libcrux_ml_kem.Vector.Portable.fsti
libcrux-ml-kem/proofs/fstar/extraction/Libcrux_ml_kem.Vector.Traits.fsti
libcrux-ml-kem/proofs/fstar/extraction/Makefile
libcrux-ml-kem/src/polynomial.rs
libcrux-ml-kem/src/sampling.rs
libcrux-ml-kem/src/serialize.rs
libcrux-ml-kem/src/vector/traits.rs
sys/platform/proofs/fstar/extraction/Libcrux_platform.X86.fsti

This PR makes the functions in sampling.rs panic-free (except for sample_from_xof that utilizes Rust_primitives.f_while_loop). It's based on hax `fold-step-boundary` branch to fix index boundary for `Rust_primitives.Hax.Folds.fold_range_step_by`.

Make functions in sampling.rs panic-free

---

libcrux-ml-dsa/benches/manual65.rs
libcrux-ml-dsa/benches/manual87.rs
libcrux-ml-dsa/src/ml_dsa_65.rs
libcrux-ml-dsa/src/ml_dsa_87.rs
libcrux-ml-dsa/src/ml_dsa_generic/instantiations.rs

I was wondering why seemingly none of the changes in the NTT I tried had any effect on ML-DSA 44, until I actually looked at the functions that are called using samply. Turns out we were using the portable NTT in ML-DSA 44 because the instantiation had a typo.
I've taken this opportunity to extend multiplexing to the other variants as well.

[ML-DSA] Repair / Extend multiplexing

---

libcrux-ml-kem/cg/fuzz/dec_fuzz.cc

Missing `static` qualifier on the private keys used for fuzzing.
Spotted by the Qualys Security Advisory team

Private keys should persist between invocations

---

libcrux-ml-kem/proofs/fstar/extraction/Libcrux_ml_kem.Hash_functions.Avx2.fsti
libcrux-ml-kem/proofs/fstar/extraction/Libcrux_ml_kem.Hash_functions.Neon.fsti
libcrux-ml-kem/proofs/fstar/extraction/Libcrux_ml_kem.Hash_functions.Portable.fsti
libcrux-ml-kem/proofs/fstar/extraction/Libcrux_ml_kem.Hash_functions.fsti
libcrux-ml-kem/proofs/fstar/extraction/Libcrux_ml_kem.Ind_cpa.fst
libcrux-ml-kem/proofs/fstar/extraction/Libcrux_ml_kem.Ind_cpa.fsti
libcrux-ml-kem/proofs/fstar/extraction/Libcrux_ml_kem.Ntt.fst
libcrux-ml-kem/proofs/fstar/extraction/Libcrux_ml_kem.Ntt.fsti
libcrux-ml-kem/proofs/fstar/extraction/Libcrux_ml_kem.Sampling.fst
libcrux-ml-kem/proofs/fstar/extraction/Libcrux_ml_kem.Sampling.fsti
libcrux-ml-kem/proofs/fstar/extraction/Libcrux_ml_kem.Serialize.fst
libcrux-ml-kem/proofs/fstar/extraction/Libcrux_ml_kem.Serialize.fsti
libcrux-ml-kem/proofs/fstar/extraction/Libcrux_ml_kem.Variant.fsti
libcrux-ml-kem/proofs/fstar/spec/Spec.MLKEM.Math.fst
libcrux-ml-kem/proofs/fstar/spec/Spec.MLKEM.fst
libcrux-ml-kem/proofs/fstar/spec/Spec.Utils.fst
libcrux-ml-kem/src/hash_functions.rs
libcrux-ml-kem/src/ind_cpa.rs
libcrux-ml-kem/src/ntt.rs
libcrux-ml-kem/src/sampling.rs
libcrux-ml-kem/src/serialize.rs
libcrux-ml-kem/src/variant.rs

This PR adds spec for unpacked functions and writes full proofs for Ind_cpa functions.
Note there's a mismatch between the spec and implementation for `generate_keypair` function, I will confirm the right procedure and upload the changes for this function.

Add proofs for Ind_cpa functions

---

.github/workflows/c.yml
.github/workflows/s390x.yml
libcrux-ml-kem/c/CMakeLists.txt
libcrux-ml-kem/cg/CMakeLists.txt
libcrux-ml-kem/cg/eurydice_glue.h
libcrux-ml-kem/cg/karamel/endianness.h

The C code in the cg directory was minimal and dropped all the endianness support.
This PR also disables benchmarks by default for the C code. They can be enabled with `LIBCRUX_BENCHMARKS=1`.
Fixes #643

Fix big-endian support in cg

---

curve25519/src/lib.rs
ed25519/src/hacl/ed25519.rs
ed25519/src/lib.rs
hacl-rs/src/bignum/base.rs
hacl-rs/src/bignum/bignum256.rs
hacl-rs/src/bignum/bignum256_32.rs
hacl-rs/src/bignum/bignum32.rs
hacl-rs/src/bignum/bignum4096.rs
hacl-rs/src/bignum/bignum4096_32.rs
hacl-rs/src/bignum/bignum64.rs
hacl-rs/src/bignum/bignum_base.rs
hacl-rs/src/lib.rs
hacl-rs/src/lowstar/endianness.rs
hacl-rs/src/streaming_types.rs
libcrux-ecdh/src/ecdh.rs
libcrux-hkdf/src/hacl.rs
libcrux-hkdf/src/hkdf.rs
libcrux-hkdf/src/impl_hacl.rs
libcrux-hmac/src/hacl/hash_sha1.rs
libcrux-hmac/src/hacl/hmac.rs
libcrux-hmac/src/hmac.rs
libcrux-kem/src/kem.rs
sha2/src/hacl.rs
sha2/src/impl_hacl.rs
sha2/src/lib.rs
sys/hacl/src/lib.rs
sys/libjade/src/lib.rs
sys/pqclean/src/lib.rs
traits/src/lib.rs

This makes good progress on https://github.com/cryspen/libcrux/issues/313. Some have been skipped to avoid merge conflicts.

Make most crates no_std

---

.github/workflows/hax.yml

This PR adds a `hax_rev` input for the workflow dispatch argument of the hax ci job.
This is useful for us on hax, e.g. for https://github.com/hacspec/hax/pull/1151, being able to run exactly the CI of libcrux:hax on a given branch is helping me a lot.

feat(ci/hax): allow manual workflows to specify hax version

---

libcrux-ml-dsa/benches/bench_utils.rs
libcrux-ml-dsa/src/hash_functions.rs
libcrux-ml-dsa/src/matrix.rs

Adding the missig inlines to `hash_functions.rs` again to get back some speed.

[ML-DSA] Inline hash_functions.rs

---

libcrux-ml-kem/src/polynomial.rs
libcrux-ml-kem/src/vector/traits.rs

This PR updates some hardcoded identifiers for impl expressions in F* quotes within the Rust code.
The identifiers changed because of https://github.com/hacspec/hax/pull/1215; those identifiers are sensible to the structure of some datatypes in the hax frontend and are expected to change whenever the THIR structure changes.

fix: fstar inlined code: refresh impl expr ID

---

flake.lock
flake.nix

Until now, the lack of these two in PATH caused two inconsequential errors:
```
ml-kem> c.sh: line 87: git: command not found
ml-kem> c.sh: line 91: fstar.exe: command not found
```
They're fine to ignore but misleading when trying to debug a build, so this PR fixes them.

Add git and fstar in PATH when building with nix

---

Cargo.toml
Readme.md
libcrux-kem/src/kem.rs
src/aead.rs
src/digest.rs
src/drbg.rs
src/hacl/aesgcm.rs
src/hacl/sha3.rs
src/hpke/aead.rs
src/hpke/errors.rs
src/hpke/hpke.rs
src/hpke/kdf.rs
src/hpke/kem.rs
src/lib.rs
src/signature.rs

This is a quick step towards `no_std` support for libcrux, which is necessary e.g. for https://github.com/cryspen/bertie/issues/126
We do still assume presence of a global allocator for the `no_std` target in question, and I've made a note of that in the Readme.

`no_std` support (via `alloc`)

---

.github/workflows/mldsa.yml
libcrux-ml-dsa/Cargo.toml
libcrux-ml-dsa/benches/bench_utils.rs
libcrux-ml-dsa/benches/manual44.rs
libcrux-ml-dsa/benches/manual65.rs
libcrux-ml-dsa/benches/manual87.rs
libcrux-ml-dsa/benches/ml-dsa.rs

This updates the pqclean benchmarks to use ml-dsa rather than dilithium.

ML-DSA: update benchmarks pqclean

---

libcrux-ml-dsa/cg/code_gen.txt
libcrux-ml-dsa/cg/header.txt
libcrux-ml-dsa/cg/libcrux_core.h
libcrux-ml-dsa/cg/libcrux_mldsa65_avx2.h
libcrux-ml-dsa/cg/libcrux_mldsa65_portable.h
libcrux-ml-dsa/cg/libcrux_sha3_avx2.h
libcrux-ml-dsa/cg/libcrux_sha3_portable.h
libcrux-ml-dsa/proofs/fstar/extraction/Libcrux_ml_dsa.Encoding.Signature.fst
libcrux-ml-dsa/src/encoding/signature.rs

Since we can use returns now, we can change these while loops into nicer for loops. This also removes a particularly ugly piece of C code that eurydice generates.
This also addresses a comment from @karthikbhargavan in #732 and should make this function easier to prove.
Related charon issue (C control flow): https://github.com/AeneasVerif/charon/issues/507

Update ML-DSA Signature deserialize

---

.github/workflows/hax.yml

This commit pins the version of nix-installer, so that we don't hit https://github.com/DeterminateSystems/nix-installer-action/issues/133. We should revert this commit whenever https://github.com/DeterminateSystems/nix-installer-action/issues/133 is closed.
Fixes #747

fix(nix ci): regression in nix-installer-action

---

.github/workflows/hax.yml

https://github.com/DeterminateSystems/nix-installer-action/issues/133 is fixed (well, https://github.com/DeterminateSystems/nix-installer/issues/1388, but that's the same issue), thus this PR reverts cryspen/libcrux#748
Fixes #749.

Revert "fix(nix ci): regression in nix-installer-action"

---

Readme.md
src/drbg.rs

This allows users of the `std` to have a minimum supported Rust version of `1.78.0` as opposed to `1.81.0`.

Use `std::error::Error` in `std` feature

---

libcrux-ml-kem/proofs/fstar/extraction/Libcrux_ml_kem.Ind_cpa.fst
libcrux-ml-kem/src/ind_cpa.rs

This patch increases z3rlimit for certain functions in ind-cpa module to fix verification process

[ML-KEM/IND-CPA ] Fix verification

---

.github/workflows/hax.yml

Towards #585 and #733 
This PR uses the hax action and splits the action into multiple steps
- extraction: `hax.py extract`
- diff
- lax: `hax.py prove --admit`
Based on this we can add verification with `hax.py prove` for ML-KEM and ML-DSA.

Update hax CI

---

.docker/c/Dockerfile
.docker/c/setup.sh
.github/workflows/docker-c.yml

This pull request creates the first GitHub Actions workflow for the C extraction Docker container, outlined in #417:
- Build the Docker image, and publish it to GitHub packages with `unstable` tag
- Use the new Docker image to extract C code, and run tests on newly extracted C code
This PR does not contain the second workflow from #417, which will publish the image under the `latest` tag, and will be run after all the tests in this first workflow pass.

Build C extraction Docker image and run tests on CI

---

src/hpke/hpke.rs
tests/xwing_kem.rs

Both in version 2 and in version 6 (the current version at the time of writing), encap of XWing should take 64 bytes of randomness, where it uses the first 32 bytes for ML-KEM and the second 32 bytes for X25519. Right now, it uses the first 32 bytes for both ML-KEM _and_ X25519. This PR fixes that.

Fix randomness consumption in XWing draft 2 implementation

---

.github/workflows/c.yml

This PR modifies the `c.yml` Github Actions workflow, adding a job (`report-status-all`) that returns a 'success' status if all of the tests ran successfully, or if they were skipped. This allows completion of this workflow to be easily required as a status check in the branch protection rules.
* Also adds an intermediate job (`report-status-tests`) that checks if all tests ran successfully.

Add status at the end of `c.yml` workflow run

---

benchmarks/Cargo.toml
benchmarks/benches/p256.rs
benchmarks/benches/x25519.rs

This PR replaces the `libcrux::ecdh` API calls in the benchmarks with calls to the `libcrux_ecdh` (top-level crate) API.
Resolves #763

Update benchmarks to use `libcrux_ecdh` API

---

ed25519/Cargo.toml
ed25519/tests/ed25519.rs

This PR adds tests for the `libcrux-ed25519` crate, adapted from the tests in `tests/ed25519.rs`. 
- Skips `wycheproof` tests whose provided signature has a length not equal to 64 bytes
- Skips `wycheproof` test groups whose provided private key has a length not equal to 32 bytes
Resolves #798

Adapt ed25519 tests to top-level crate API

---

chacha20poly1305/src/impl_hacl.rs
chacha20poly1305/tests/chachapoly.rs

@wysiwys pointed out that the decrypt benchmarks are failing, so we jumped on a call to fix this. The issue was that we were using passing the length including the MAC tag to the hacl function, but the buffer only contained the ciphertext without the tag.
This PR changes the code to use the correct length (the length of `ctxt_cpa` instead of `ctxt`).
As a followup I filed an issue to add a test that fails if we use the wrong value here: https://github.com/cryspen/libcrux/issues/822.

fix: chachapoly: use the correct ciphertext length

---

chacha20poly1305/Cargo.toml
chacha20poly1305/tests/chachapoly.rs
tests/chachapoly.rs

Migrate remaining Chacha20Poly1305 tests to new crate structure

---

benchmarks/benches/x25519.rs

This pull request updates the `x25519` benchmarks to use the `libcrux_ecdh::x25519...` API where possible.
- `libcrux_ecdh::x25519_key_gen()` for generating (private, public) key pairs
-  `libcrux_ecdh::x25519_generate_secret()` for generating individual private keys, when needed

Use the `libcrux_ecdh::x25519...` API for key generation

---

benchmarks/Cargo.toml
benchmarks/benches/ed25519.rs

Add benchmarks for `libcrux_ed25519`.
Benchmark `libcrux_ed25519::sign()` and `libcrux_ed25519::verify()` against equivalent functionality from:
- `ring`
- `openssl`
- `ed25519-dalek`
Resolves #827

Add benchmarks for `libcrux_ed25519`

---

.github/workflows/mlkem-build-test.yml
.github/workflows/mlkem-c.yml

This pull request implements two small fixes to the merge queue:
- Fix the incorrect indentation in `mlkem-c.yml` (syntax error that caused the workflow to fail)
- Do not run ML-KEM fuzz test job on pull requests
- This fix also adds a new status check: `mlkem-fuzz-status` (complete list in #544)

Merge queue: fix indentation and do not run ML-KEM fuzz test on pull requests

---

.github/workflows/mlkem-bench.yml

This PR removes the step to clear `Cargo.lock` in the ML-KEM benchmark workflow, since this file is no longer tracked in git.

[CI] Fix for ML-KEM benchmark: remove step to clear `Cargo.lock`

---

Cargo.toml
libcrux-intrinsics/Cargo.toml
libcrux-ml-dsa/Cargo.toml
libcrux-ml-kem/Cargo.toml
libcrux-sha3/Cargo.toml

This PR:
- updates `hax-lib`
- defines a workspace dependency `hax-lib`, so that there is only one version of `hax-lib` in the repo

`hax-lib`: update to `0.2.0`

---

.github/workflows/mldsa-c.yml
.github/workflows/mlkem-c.yml

This PR fixes a bug in the `mlkem-c.yml` and `mldsa-c.yml` workflows where the last status check job would succeed if its predecessor job was skipped, which could happen if one of its predecessor jobs failed. 
The fix is to remove the intermediate job and make the final check depend on the required jobs.

[merge queue] fix checks succeeding on failed predecessor

---

.github/workflows/mldsa-c.yml
.github/workflows/mlkem-c.yml

This PR fixes an issue in the GitHub Actions workflows `mlkem-c.yml` and `mldsa-c.yml` where, if one of the predecessors of a status check's needed jobs fails, the status check itself may succeed, due to the earlier predecessor not being included in its `needed` list. The fix is to explicitly include all predecessors of the status check in its `needed` list.
cc #544

[Merge queue] make status checks explicitly depend on all preceding jobs in graph

---

flake.nix

This fixes the nix CI.
As a drive-by, I also ripped out the terrible hack I had made for `Cargo.lock`; it relied on a bizarre state of the git repo which caused unending frustration.

Use clang-format of clang 18

---

libcrux-sha3/benches/sha3.rs
libcrux-sha3/src/generic_keccak.rs
libcrux-sha3/src/portable_keccak.rs
libcrux-sha3/src/simd/arm64.rs
libcrux-sha3/src/simd/avx2.rs
libcrux-sha3/src/traits.rs

This PR makes three main changes:
* switches the SHA-3 internal state to a flat array of 25 u64s
* generalizes access to this state using `get` and `set` functions.
* stores the state in column-major order (to try to get some locality for rho/theta)

Flatten SHA-3 state and switch row/column

---

blake2/Cargo.toml
blake2/src/impl_hacl/error.rs
blake2/src/lib.rs

This lets users that don't need `no_std` use an older version of Rust, because they don't need to use `error_in_core`. This was an issue for Rosenpass specifically.

blake2: make no_std optional using default std feature

---

.github/workflows/mlkem-bench.yml

This PR updates the ML-KEM benchmarks workflow to use the new benchmarking actions ([extract](https://github.com/cryspen/benchmark-data-extract-transform/) and  [upload](https://github.com/cryspen/benchmark-upload-and-plot-action)).
This is part of the CI cleanup in #544

Update ML-KEM benchmarking workflow to use new benchmarking actions

---

Cargo.toml
macros/src/lib.rs
test-utils/Cargo.toml
test-utils/README.md
test-utils/src/lib.rs
test-utils/src/tracing.rs
test-utils/tests/trace.rs
test-utils/tests/tracing_macros.rs

This PR adds the tracing tools we agreed on adding at our meeting yesterday. It adds the new crate `libcrux-test-utils`, which contains  the tracing library, and the new `trace_span` proc macro to `libcrux-macros`.

Add tracing types and a proc macro for using it to measure functions

---

libcrux-ml-kem/src/polynomial.rs
libcrux-ml-kem/src/vector/traits.rs

This PR updates some (hardcoded, we have no better way currently, see https://github.com/cryspen/hax/issues/1398) instance identifiers.
Those changed because of cryspen/hax#1391 which is updating the rustc pin: instance identifiers are hashes, so subtle changes to the AST make them change.
Note: th failure of hax-related jobs here is expected. I will bypass hax CI to get cryspen/hax#1391 in, then we will merge that PR.
I'm waiting on your approval @franziskuskiefer to bypass hax CI on cryspen/hax#1391, so that we can merge this PR right after.

fix(F*): rename instance ids, following cryspen/hax#1391

---

Cargo.toml
ecdsa/Cargo.toml
ed25519/Cargo.toml
libcrux-ecdh/Cargo.toml
libcrux-hkdf/Cargo.toml
libcrux-hmac/Cargo.toml
libcrux-kem/Cargo.toml
libcrux-ml-kem/Cargo.toml
libcrux-psq/Cargo.toml
p256/Cargo.toml
p256/src/lib.rs
rsa/Cargo.toml
sha2/Cargo.toml
traits/Cargo.toml

This PR makes the following crates `no_std`-compatible by default:
- `libcrux-traits`
- `libcrux-sha2`
- `libcrux-p256`
It also adds `no_std` support for the following crates (which can be activated with `default-features = false`):
- `libcrux-ml-kem`
- `libcrux-kem`
- `libcrux-ecdh`
Version numbers are also updated where needed.

Add `no_std` support to additional libcrux crates

---

fstar-helpers/Makefile.base
fstar-helpers/tactics/Tactics.Circuits.fst

This commit introduces the `Tactics.Circuits` module, which provides a structured set of tactics to assist in the normalization and rewriting of *circuit-like* expressions—i.e., computations over statically-finite collections where control flow can be statically eliminated.
We define a statically-finite collection is a data structure that contains a collection of items indexable on a domain `D` which is statically known.
This is a tactic that visits the goal top-down, visiting each `match scrutinee with | ... (arms)` expression.
For each `match`es, the tactic normalizes fully `scrutinee`, leaving the arms untouched.
Rewrite the goal, lifting _source functions_ that operates on _source types_ `Si` to a set of equivalent _destination functions_ operating on _destination types_ `Di`.
The …

feat(fstar-helpers): introduce module `Tactics.Circuits`

---

fstar-helpers/minicore/src/abstractions/bitvec.rs
fstar-helpers/minicore/src/abstractions/funarr.rs
fstar-helpers/minicore/src/core_arch/x86.rs
fstar-helpers/minicore/src/core_arch/x86/interpretations.rs
fstar-helpers/minicore/src/core_arch/x86/opaque.rs
fstar-helpers/minicore/src/lib.rs

> Note: this is a remake of https://github.com/cryspen/libcrux/pull/923
This PR introduces an interpretation layer for SIMD-style machine integer vectors (`i32x8`, `i64x4`) over `BitVec<256>`, along with modeling support for selected AVX2 intrinsics.
- **`int_vec_interp` module** (`bitvec.rs`):
- Defines type aliases `i32x8` and `i64x4` as `FunArray`s over `i32` and `i64`.
- Implements `From` conversions between `BitVec<256>` and these vector types.
- Adds cancelation lemmas for round-trip conversions.
- **`core_arch::x86::interpretations` module**:
- Models a subset of AVX2 intrinsics over `i32x8`/`i64x4`:
- `_mm256_set1_epi32`
- `_mm256_mul_epi32`
- `_mm256_sub_epi32`
- `_mm256_shuffle_epi32`
- `_mm256_blend_epi32`
- Defines lift lemmas that link the intrinsics with the interpreted …

Minicore: add a integer vector interpretation for bitvecs and (some) avx2 intrinsics

---

Cargo.toml
fstar-helpers/minicore/src/core_arch/x86.rs
fstar-helpers/tactics/Tactics.Circuits.fst
libcrux-intrinsics/src/avx2.rs
libcrux-ml-dsa/proofs/fstar/extraction/Libcrux_ml_dsa.Simd.Avx2.Arithmetic.Expanded.fst
libcrux-ml-dsa/proofs/fstar/extraction/Makefile
libcrux-ml-dsa/src/simd/avx2/arithmetic.rs

This PR makes F* normalize `montgomery_mulitply` so that it becomes a flat circuit.
This PR also adds a file `Libcrux_mld_dsa.Simd.Avx2.Arithmetic.fst`, which contains the fully expanded version of `montgomery_mulitply`, and a proof of equivalence.
Fixes https://github.com/cryspen/libcrux/issues/942.

ML-DSA: proofs: `montgomery_multiply`: flatten circuit

---

secrets/src/int/secret_integers.rs
secrets/src/lib.rs

This PR adds explicit `no_std` support to the `libcrux-secrets` crate by adding the `no_std` crate-level attribute, and replacing `std::ops` with `core::ops`.
Closes #978

Add explicit `no_std` support to the `libcrux-secrets` crate

---

.github/workflows/mldsa-bench.yml
.github/workflows/mlkem-bench.yml

Restores the original configuration of the benchmark chart action, so that benchmark results are written to the `gh-pages` branch in this repository.
Resolves #973

[CI] Push ML-KEM and ML-DSA benchmark results to `gh-pages` branch in this repository

---

fstar-helpers/Makefile.base
fstar-helpers/Makefile.generic
libcrux-ml-dsa/proofs/fstar/extraction/Makefile

This PR changes `fstar-helpers/Makefile.base` so that:
- it detects when a module is present both in `SLOW_MODULES` and `VERIFIED_MODULES` or `ADMIT_MODULES`.
- it adds `SLOW_MODULES` to `VERIFIED_MODULES` when `VERIFY_SLOW_MODULES` is `yes`.
This PR also fixes the makefile in mldsa: `ADMIT_MODULES` was populated with every module not in `VERIFIED_MODULES`. We need to filter out those present in `SLOW_MODULES` as well.
There was a duplicated make rule because of this, which was breaking emacs/vscode integration.
This PR also adds a `check/myfile.fst`, that checks up to `myfile.fst`. This is a shortcut for `make repo/.fstar-cache/checked/myfile.fst.checked`

F*: improve makefile, detect duplicates in `SLOW_MODULES`

---

sys/hacl/build.rs
sys/hacl/c/src/Lib_Memzero0.c

This fixes #856. 
`explicit_bzero` has been in glibc since 2017

fix build warning on linux

---

flake.lock
flake.nix

- Move flake dependencies into inputs
- Add missing openssl and pkg-config dependency
- Add direct import of charon
- Update all inputs
Uses [this](https://github.com/AeneasVerif/charon/commit/98ac30155a29c6067c8299cdc88bfbadf373d1b4) update from charon to have access to rust src.

Fixes the flake to work with rust-rover IDE

---

chacha20poly1305/src/impl_hacl.rs
chacha20poly1305/tests/chachapoly.rs

This pull request adds error handling to the function `libcrux_chacha20poly1305::encrypt_detached()`, so that the function returns the error `AeadError::CiphertextTooShort` when the provided `ctxt` argument references a buffer that is too short.
This change aligns the approach to error handling used by this function with the approach used by the other encryption and decryption functions in this crate. It also prevents ths function from panicking when an invalid `ctxt` is provided.
Additionally, this pull request includes a test for this functionality. This test ensures that the public encryption/decryption functions in this crate return the correct error variants when their `ctxt` or `ptxt` arguments reference buffers that are too short:
- `encrypt_detached()` -> …

`libcrux_chacha20poly1305::encrypt_detached()`: add error handling for invalid ciphertext buffer length

---

ed25519/Cargo.toml
ed25519/src/impl_hacl.rs
libcrux-ecdh/Cargo.toml
libcrux-ecdh/src/p256_internal.rs
libcrux-ecdh/src/x25519.rs
libcrux-kem/Cargo.toml
libcrux-kem/src/kem.rs
libcrux-psq/Cargo.toml
libcrux-psq/examples/psq.rs
libcrux-psq/src/classic_mceliece.rs
libcrux-psq/src/cred.rs
libcrux-psq/src/impls.rs
libcrux-psq/src/psk_registration.rs
libcrux-psq/src/traits.rs

This PR replaces almost all ad hoc serialization and deserialization in PSQv1 with TLSCodec (the exception being the timestamp included in the initiator message).
To this end, I've introduced `codec` features in `libcrux-ecdh`, `ed25519` & `libcrux-kem`.
Fixes #925

[PSQ] Use TLSCodec for Serialization/Deserialization in PSQv1

---

libcrux-ml-dsa/cg/intrinsics/libcrux_intrinsics_avx2.h
libcrux-ml-kem/cg/intrinsics/libcrux_intrinsics_avx2.h

This has been fixed before but never upstreamed here.
```
C:\b\s\w\ir\cache\builder\boringssl\crypto\fipsmodule\mlkem\../../../third_party/libcrux/libcrux_mlkem768_avx2.h(45): error C2220: the following warning is treated as an error
C:\b\s\w\ir\cache\builder\boringssl\crypto\fipsmodule\mlkem\../../../third_party/libcrux/libcrux_mlkem768_avx2.h(45): warning C4003: not enough arguments for function-like macro invocation 'libcrux_intrinsics_avx2_mm256_setzero_si256'
C:\b\s\w\ir\cache\builder\boringssl\crypto\fipsmodule\mlkem\../../../third_party/libcrux/libcrux_mlkem768_avx2.h(314): warning C4003: not enough arguments for function-like macro invocation 'libcrux_intrinsics_avx2_mm256_setzero_si256'
```

c: avoid warning C4003 in msvc in intrinsics macro

---

fstar-helpers/Makefile.generic

This PR changes two things in the default Makefile. 
- `FINDLIBS_OUTPUT ?=` makes it possible to disable automatic import of modules in a makefile using the default one.
- Prevent the `clean` to run the build target and remove more auxiliary files 
PR https://github.com/cryspen/libcrux/pull/1092 is based on these two commits.

Makefile improvement

---

CONTRIBUTING.md

This PR adds an entry for `/crates/testing` to the directory structure outlined in `CONTRIBUTING.md`, for containing testing-related crates. It also moves the entry for the `libcrux-test-utils` into `/crates/testing`.
Another option would be to just include all the testing crates in the `/crates/utils` folder.

`CONTRIBUTING.md`: Add `/crates/testing` to directory structure

---

blake2/src/impl_digest_trait.rs
blake2/tests/blake2.rs
sha2/src/impl_digest_trait.rs
sha2/tests/sha2.rs
traits/src/digest.rs

This PR adds more convenient APIs for initializing the digest state associated with an implementor `D` of `DigestIncrementalBase`. A `D::IncrementalState` can now be initialized by calling the `new()` method.
A new API is also added to `libcrux_traits::digest::Hasher`, that builds on this API:
```rust
/// Initialize a hasher.
pub fn new() -> Self {
Self {
state: D::IncrementalState::new(),
}
}
``` 
Using `Hasher::new()` to initialize hashers:
```rust
// type aliases for `libcrux_traits::digest::Hasher<_,_>`
let mut hasher = libcrux_sha2::Sha256Hasher::new();
let mut hasher = libcrux_blake2::Blake2sHasher::<32>::new();
```
Additionally, the tests in the `blake2` and `sha2` crates are updated to include tests for this API.
This PR is based on the branch in:
- …

Add API for initializing digest state

---

traits/src/ecdh/arrayref.rs
traits/src/ecdh/owned.rs
traits/src/ecdh/slice.rs

This is just a convenience that saves you from doing the same manually.

Add provided method `generate_pair` to ECDH traits

---

hacl-rs/src/bignum/bignum256.rs
hacl-rs/src/bignum/bignum256_32.rs
hacl-rs/src/bignum/bignum32.rs
hacl-rs/src/bignum/bignum4096.rs
hacl-rs/src/bignum/bignum4096_32.rs
hacl-rs/src/bignum/bignum64.rs

First step towards #344.
This fixes a lot of warnings resulting from literal translation of HACL comments, which clutter up the doc output for the  other crates.
I did not change the content of the comments beyond what's needed to silence the warning, in particular, I did not e.g. change `uint64_t[8]` to an equivalent Rust type.

Fix doc warnings in `libcrux-hacl-rs`
