cryspen/libcrux

.github/workflows/rust.yml
Cargo.toml
benches/aead.rs
benches/drbg.rs
benches/sha2.rs
benches/sha3.rs
benches/x25519.rs
src/ecdh.rs
src/hpke/kem.rs
src/hw_detection/cpuid.rs
src/hw_detection/test.rs
sys/libjade/.gitignore
sys/libjade/Cargo.lock
sys/libjade/Cargo.toml
sys/libjade/build.rs
tests/hpke_single_kat.rs

- fix windows build
- add more CI
- bump dev versions

build fixes

---

.github/workflows/hax.yml
src/kem/kyber768.rs

Run hax on CI for kyber to ensure that it's not breaking.

run hax on ci

---

benches/kyber768.rs
src/kem/kyber/constants.rs
src/kem/kyber/ntt.rs
src/kem/kyber/sampling.rs
src/kem/kyber/serialize.rs

Unrolling the NTT layer loops to gain ~5% performance.

kyber unroll loops

---

src/ecdh.rs
src/hacl/curve25519.rs
src/hacl/p256.rs
src/hpke/kem.rs
src/kem.rs
src/signature.rs
sys/hacl/build.rs

This ports some improvements from the dev branch to main and exposes some additional functions to make this usable in [Bertie](https://github.com/cryspen/bertie/tree/libcrux_backend).

Port improvements from dev

---

kyber-crate.sh

A simple shell script to pull out kyber as a separate crate for Aeneas.
cc @protz

kyber crate extraction script

---

build.rs
src/signature.rs
sys/hacl/build.rs

Set some more platform dependent flags for hacl.

hacl build update

---

proofs/fstar/extraction-edited.patch
proofs/fstar/extraction-secret-independent.patch
proofs/fstar/extraction/Libcrux.Kem.Kyber.Ntt.fsti

Following the change from https://github.com/hacspec/hax/pull/555.

chore(hax/kyber): regenerate F* & patches

---

proofs/fstar/extraction-edited.patch
proofs/fstar/extraction-secret-independent.patch
proofs/fstar/extraction/Libcrux.Kem.Kyber.Ntt.fst

Following https://github.com/hacspec/hax/pull/559
**Note**: the CI will be red until https://github.com/hacspec/hax/pull/559 is merged

chore(hax/kyber): extract & patches 

---

libcrux-ml-kem/src/arithmetic.rs
libcrux-ml-kem/src/compress.rs
libcrux-ml-kem/src/ind_cpa.rs
libcrux-ml-kem/src/intvec.rs
libcrux-ml-kem/src/intvec128.rs
libcrux-ml-kem/src/intvec32.rs
libcrux-ml-kem/src/lib.rs
libcrux-ml-kem/src/matrix.rs
libcrux-ml-kem/src/ntt.rs
libcrux-ml-kem/src/polynomial.rs
libcrux-ml-kem/src/sampling.rs
libcrux-ml-kem/src/serialize.rs

Please check that I didn't mess up anything. Then we can merge this into dev.

abstract polynomial setup

---

proofs/fstar/extraction-edited.patch
proofs/fstar/extraction-secret-independent.patch
proofs/fstar/extraction/Libcrux.Digest.Incremental_x4.fsti
proofs/fstar/extraction/Libcrux.Digest.fsti
proofs/fstar/extraction/Libcrux.Kem.Kyber.Arithmetic.fsti
proofs/fstar/extraction/Libcrux.Kem.Kyber.Compress.fsti
proofs/fstar/extraction/Libcrux.Kem.Kyber.Constant_time_ops.fsti
proofs/fstar/extraction/Libcrux.Kem.Kyber.Constants.fsti
proofs/fstar/extraction/Libcrux.Kem.Kyber.Hash_functions.fsti
proofs/fstar/extraction/Libcrux.Kem.Kyber.Ind_cpa.fsti
proofs/fstar/extraction/Libcrux.Kem.Kyber.Kyber1024.fsti
proofs/fstar/extraction/Libcrux.Kem.Kyber.Kyber512.fsti
proofs/fstar/extraction/Libcrux.Kem.Kyber.Kyber768.fsti
proofs/fstar/extraction/Libcrux.Kem.Kyber.Matrix.fsti
proofs/fstar/extraction/Libcrux.Kem.Kyber.Ntt.fsti
proofs/fstar/extraction/Libcrux.Kem.Kyber.Sampling.fsti
proofs/fstar/extraction/Libcrux.Kem.Kyber.Serialize.fsti
proofs/fstar/extraction/Libcrux.Kem.Kyber.Types.fst
proofs/fstar/extraction/Libcrux.Kem.Kyber.fsti

updated extraction with latest hax and fixed patches

---

libcrux-ml-kem/examples/decapsulate.rs
libcrux-ml-kem/examples/keygen.rs

This PR adds examples for decapsulate and keygen to better profile performance.

more examples

---

polynomials-avx2/src/lib.rs
polynomials-avx2/src/portable.rs

Reverts cryspen/libcrux#263
This is actually failing tests.

Revert "Kyber AVX2 implementations of serialization and montgomery reduction"

---

.github/workflows/mlkem.yml
libcrux-ml-kem/Cargo.toml
libcrux-ml-kem/build.rs
libcrux-ml-kem/src/ind_cca.rs
polynomials-avx2/src/debug.rs
polynomials-avx2/src/lib.rs
polynomials/Cargo.toml
polynomials/build.rs
polynomials/src/lib.rs

This PR enables simd features automatically and cleans up the build for it.
It also adds the mlkem crate to the ci, always using the available features.

mlkem crate feature detection & ci

---

proofs/fstar/extraction-edited.patch
proofs/fstar/extraction-secret-independent.patch
proofs/fstar/extraction/Libcrux.Digest.Incremental_x4.fsti

This PR is required for https://github.com/hacspec/hax/pull/666, and https://github.com/hacspec/hax/pull/666 requires this PR, so we need to disable a CI workflow somewhere

chore: regenerate patches

---

proofs/fstar/extraction-edited.patch
proofs/fstar/extraction-secret-independent.patch
proofs/fstar/extraction/Libcrux.Kem.Kyber.Arithmetic.fst
proofs/fstar/extraction/Libcrux.Kem.Kyber.Arithmetic.fsti
proofs/fstar/extraction/Libcrux.Kem.Kyber.Constant_time_ops.fst
proofs/fstar/extraction/Libcrux.Kem.Kyber.Hash_functions.fst
proofs/fstar/extraction/Libcrux.Kem.Kyber.Ind_cpa.fst
proofs/fstar/extraction/Libcrux.Kem.Kyber.Matrix.fst
proofs/fstar/extraction/Libcrux.Kem.Kyber.Ntt.fst
proofs/fstar/extraction/Libcrux.Kem.Kyber.Ntt.fsti
proofs/fstar/extraction/Libcrux.Kem.Kyber.Sampling.fst
proofs/fstar/extraction/Libcrux.Kem.Kyber.Sampling.fsti
proofs/fstar/extraction/Libcrux.Kem.Kyber.Serialize.fst
proofs/fstar/extraction/Libcrux.Kem.Kyber.Types.fst
proofs/fstar/extraction/Libcrux.Kem.Kyber.fst

For this one we need to bypass the hax jobset in the CI

Regenerate patches following PR hacspec/hax#679

---

.github/workflows/nix.yml

- run `nix.yml` on pull requests
- use nix cache

CI: update `nix.yml`

---

.github/workflows/reviews.yml

Dismiss old reviews on PRs to make GH more usable.

Workflow to dismiss stale reviews

---

.github/workflows/c.yml
.github/workflows/checks.yml
.github/workflows/ecdh.yml
.github/workflows/hax.yml
.github/workflows/kem.yml
.github/workflows/mldsa.yml
.github/workflows/mlkem.yml
.github/workflows/nix.yml
.github/workflows/platform.yml
.github/workflows/rust.yml
.github/workflows/specs.yml

I've also noticed that I previously didn't include the specs workflow on the queue, which I've done now.

Report merge queue status

---

libcrux-ml-dsa/src/ntt.rs

Just a drive-by. This appears to speed things up a tiny bit for me.

make invert_ntt_at_layer_3_plus in ml-dsa generic

---

.docker/c/install.sh

Bump Eurydice to latest version in Docker image

---

libcrux-ml-kem/c.sh
libcrux-ml-kem/c/spdx-header.txt
libcrux-ml-kem/cg/spdx-header.txt

Add libcrux revision, license and copyright to the C headers.
This requires aeneasverif/eurydice#43

better header for ml-kem C extraction

---

libcrux-ml-dsa/Cargo.toml
libcrux-ml-dsa/benches/ml-dsa.rs
libcrux-ml-dsa/examples/sign_65.rs
libcrux-ml-dsa/examples/verify_65.rs
libcrux-ml-dsa/src/encoding/commitment.rs
libcrux-ml-dsa/src/encoding/error.rs
libcrux-ml-dsa/src/encoding/gamma1.rs
libcrux-ml-dsa/src/encoding/signature.rs
libcrux-ml-dsa/src/encoding/signing_key.rs
libcrux-ml-dsa/src/encoding/t0.rs
libcrux-ml-dsa/src/encoding/t1.rs
libcrux-ml-dsa/src/encoding/verification_key.rs
libcrux-ml-dsa/src/hash_functions.rs
libcrux-ml-dsa/src/instantiations.rs
libcrux-ml-dsa/src/lib.rs
libcrux-ml-dsa/src/matrix.rs
libcrux-ml-dsa/src/ml_dsa_44.rs
libcrux-ml-dsa/src/ml_dsa_65.rs
libcrux-ml-dsa/src/ml_dsa_87.rs
libcrux-ml-dsa/src/ml_dsa_generic.rs
libcrux-ml-dsa/src/ntt.rs
libcrux-ml-dsa/src/sample.rs
libcrux-ml-dsa/src/simd.rs
libcrux-ml-dsa/src/types.rs
libcrux-ml-dsa/tests/nistkats.rs
libcrux-ml-dsa/tests/self.rs
libcrux-ml-dsa/tests/wycheproof_sign.rs
libcrux-ml-dsa/tests/wycheproof_verify.rs

This is the first PR in a series to make ML-DSA multiplex between avx2, neon, and portable implementations.
cc #275

Start multiplexing for ML-DSA

---

LICENSE-MIT

Add LICENSE-MIT

---

.gitignore
Cargo.lock
fstar-helpers/Makefile.base
fstar-helpers/README.md
fstar-helpers/fstar-bitvec/BitVecEq.fst
fstar-helpers/fstar-bitvec/BitVecEq.fsti
fstar-helpers/fstar-bitvec/MkSeq.fst
libcrux-ml-kem/proofs/fstar/extraction/Libcrux_ml_kem.Constant_time_ops.fst
libcrux-ml-kem/proofs/fstar/extraction/Libcrux_ml_kem.Ind_cca.Unpacked.fst
libcrux-ml-kem/proofs/fstar/extraction/Libcrux_ml_kem.Ind_cca.fst
libcrux-ml-kem/proofs/fstar/extraction/Libcrux_ml_kem.Ind_cpa.fst
libcrux-ml-kem/proofs/fstar/extraction/Libcrux_ml_kem.Invert_ntt.fst
libcrux-ml-kem/proofs/fstar/extraction/Libcrux_ml_kem.Matrix.fst
libcrux-ml-kem/proofs/fstar/extraction/Libcrux_ml_kem.Ntt.fst
libcrux-ml-kem/proofs/fstar/extraction/Libcrux_ml_kem.Polynomial.fst
libcrux-ml-kem/proofs/fstar/extraction/Libcrux_ml_kem.Sampling.fst
libcrux-ml-kem/proofs/fstar/extraction/Libcrux_ml_kem.Serialize.fst
libcrux-ml-kem/proofs/fstar/extraction/Libcrux_ml_kem.Types.fsti
libcrux-ml-kem/proofs/fstar/extraction/Libcrux_ml_kem.Vector.Avx2.Sampling.fst
libcrux-ml-kem/proofs/fstar/extraction/Libcrux_ml_kem.Vector.Avx2.Serialize.fst
libcrux-ml-kem/proofs/fstar/extraction/Libcrux_ml_kem.Vector.Neon.Ntt.fst
libcrux-ml-kem/proofs/fstar/extraction/Libcrux_ml_kem.Vector.Neon.Serialize.fst
libcrux-ml-kem/proofs/fstar/extraction/Libcrux_ml_kem.Vector.Portable.Arithmetic.fst
libcrux-ml-kem/proofs/fstar/extraction/Libcrux_ml_kem.Vector.Portable.Compress.fst
libcrux-ml-kem/proofs/fstar/extraction/Libcrux_ml_kem.Vector.Portable.Sampling.fst
libcrux-ml-kem/proofs/fstar/extraction/Libcrux_ml_kem.Vector.Portable.Serialize.fst
libcrux-ml-kem/proofs/fstar/extraction/Libcrux_ml_kem.Vector.Portable.Serialize.fsti
libcrux-ml-kem/proofs/fstar/extraction/Makefile
libcrux-ml-kem/src/vector/portable/serialize.rs

This PR adds specs for serialize functions, most of them are only panic-free however.

[ML-KEM/PROOFS] serialize: specs + panic-free 

---

.cargo/config.toml
.gitignore

looks like this was accidentally commited a while back

drop config.toml

---

libcrux-ml-kem/cg/code_gen.txt
libcrux-ml-kem/cg/libcrux_core.h
libcrux-ml-kem/cg/libcrux_ct_ops.h
libcrux-ml-kem/cg/libcrux_mlkem768_avx2.h
libcrux-ml-kem/cg/libcrux_mlkem768_avx2_types.h
libcrux-ml-kem/cg/libcrux_mlkem768_portable.h
libcrux-ml-kem/cg/libcrux_mlkem768_portable_types.h
libcrux-ml-kem/cg/libcrux_sha3_avx2.h
libcrux-ml-kem/cg/libcrux_sha3_portable.h
libcrux-ml-kem/proofs/fstar/extraction/Libcrux_ml_kem.Ind_cca.Unpacked.fst
libcrux-ml-kem/proofs/fstar/extraction/Libcrux_ml_kem.Ind_cca.Unpacked.fsti
libcrux-ml-kem/proofs/fstar/extraction/Libcrux_ml_kem.Ind_cpa.fst
libcrux-ml-kem/proofs/fstar/extraction/Libcrux_ml_kem.Ind_cpa.fsti
libcrux-ml-kem/proofs/fstar/extraction/Makefile
libcrux-ml-kem/proofs/fstar/spec/Spec.MLKEM.fst
libcrux-ml-kem/src/ind_cca.rs
libcrux-ml-kem/src/ind_cpa.rs

This PR adds spec for ind-cca unpacked functions and verifies Ind-cca unpacked functions against the spec.

Proofs for Ind-cca unpacked functions

---

flake.nix

Following https://github.com/cryspen/libcrux/pull/649

Propagate recent cmake changes to nix CI

---

flake.lock
flake.nix

A few flake improvements that will make it possible to remove the `Cargo.lock` and to use it more effectively in CI.

Improve the flake

---

Cargo.toml
libcrux-ml-dsa/src/ml_dsa_generic.rs
libcrux-ml-dsa/src/sample.rs
libcrux-ml-dsa/src/samplex4.rs

This PR presents a compromise for achieving passable levels of performance and build times in Release builds, while somewhat cutting back on stack usage in Debug build.

Temporary fixes for performance/build times/stack usage for ML-DSA AVX2

---

.github/workflows/ecdh.yml
.github/workflows/kem.yml

disable macos asan

---

libcrux-ml-dsa/proofs/fstar/extraction/Libcrux_ml_dsa.Types.fst

mldsa: update F* extract

---

libcrux-intrinsics/proofs/fstar/extraction/Libcrux_intrinsics.Arm64_extract.fst
libcrux-intrinsics/proofs/fstar/extraction/Libcrux_intrinsics.Arm64_extract.fsti
libcrux-intrinsics/proofs/fstar/extraction/Libcrux_intrinsics.Avx2_extract.fst
libcrux-intrinsics/proofs/fstar/extraction/Libcrux_intrinsics.Avx2_extract.fsti
libcrux-ml-kem/proofs/fstar/extraction/Libcrux_ml_kem.Vector.Portable.Compress.fsti
libcrux-ml-kem/src/vector/portable/compress.rs
sys/platform/proofs/fstar/extraction/Libcrux_platform.Platform.fst
sys/platform/proofs/fstar/extraction/Libcrux_platform.Platform.fsti

This is a minimal change to libcrux to enable extraction with Hax #1301

Fix Annotation to enable extraction with Hax #1301

---

chacha20poly1305/src/impl_hacl.rs
libcrux-psq/Cargo.toml
libcrux-psq/src/lib.rs
libcrux-psq/src/psk_registration.rs

Use Rust chacha20 in psq and drop legacy libcrux dependency.

psq: pure rust libcrux

---

.github/workflows/mlkem-c.yml
libcrux-ml-dsa/cg/CMakeLists.txt
libcrux-ml-kem/c/CMakeLists.txt
libcrux-ml-kem/cg/CMakeLists.txt

This is currently blocking other things from being merged.

c: fixup cmake files and dependencies

---

flake.lock
flake.nix
libcrux-ml-dsa/c.sh

This will make it possible to test it in the circus CI.

Add ml-dsa to the nix flake

---

fstar-helpers/minicore/src/abstractions/funarr.rs
fstar-helpers/minicore/src/core_arch/x86.rs

Fixing some of the documentation comments in minicore.

Comment fix

---

ed25519/Cargo.toml

move wycheproof to dev dependencies in `libcrux-ed25519`

---

.github/workflows/no-std-check.yml
no-std-check.sh

[CI] Add workflow to check `no_std` compatibility for some crates

---

libcrux-ml-dsa/proofs/fstar/spec/Spec.Intrinsics.fsti
libcrux-ml-dsa/src/simd/avx2/encoding/t0.rs

This PR bumps an rlimit and simplifies a proof (that now goes through automatically).
This fixes CI.

fix(F*): rlimit in `Spec.Intrinsics`

---

libcrux-ml-dsa/cg/eurydice_glue.h
libcrux-ml-dsa/cg/intrinsics/libcrux_intrinsics_avx2.h
libcrux-ml-dsa/cg/karamel/target.h
libcrux-ml-kem/boring.sh
libcrux-ml-kem/cg/boring/eurydice_glue.h
libcrux-ml-kem/cg/boring/karamel/target.h
libcrux-ml-kem/cg/eurydice_glue.h
libcrux-ml-kem/cg/intrinsics/libcrux_intrinsics_avx2.h

A little cleanup for https://github.com/cryspen/home/issues/320.

C: minor update

---

libcrux-ml-dsa/Cargo.toml

This works toward #1124, but is not sufficient to close it.

mldsa: set publish=true in Cargo.toml

---

libcrux-ml-dsa/src/simd/portable.rs

mldsa: fix another compiler warning

---

Cargo.toml

Pin hax to exact version number.
